'use client';
// app/dashboard/_components/print-export.tsx
// batch-5-print-export
//
// Print-optimized branded PDF export for lesson notes, schemes, and exams.
// The browser already renders KaTeX math/chemistry pixel-perfectly, so the
// export path is: branded print header (mirrors src/lib/pdf/brand.js palette)
// + window.print() (users pick "Save as PDF"). No server round-trip, no
// LaTeX-in-pdfkit problem, works offline once the page is loaded.
//
// Two pieces, mounted separately by each detail page:
//   <ExportButton …>  — screen-only button (+ teacher/student toggle for exams)
//   <PrintHeader …>   — hidden on screen; the branded band + footer in print
//
// Student copy (exams): adds body.kr-student-copy during print; CSS in
// globals.css hides answer ticks, highlights, and marking guides. Zero edits
// to assessment-render needed.

import { useState } from 'react';

type School = { name?: string | null; logoUrl?: string | null } | null;

// brand.js palette — keep in sync with src/lib/pdf/brand.js
const BRAND = { green: '#33aa42', navy: '#131b26', grey: '#6b7280' };

export function ExportButton({
  filename,
  showAnswersToggle = false,
}: {
  filename: string;
  showAnswersToggle?: boolean;
}) {
  const [includeAnswers, setIncludeAnswers] = useState(true);

  function handlePrint() {
    const prevTitle = document.title;
    // Saved-PDF filename comes from the tab title in every browser.
    document.title = filename.replace(/[\\/:*?"<>|]/g, '-').slice(0, 120);

    const detailsEls = Array.from(document.querySelectorAll('details'));
    const prevOpen = detailsEls.map((d) => d.open);

    if (showAnswersToggle && !includeAnswers) {
      document.body.classList.add('kr-student-copy');
    } else {
      // Teacher copy: force marking guides open so they actually print.
      detailsEls.forEach((d) => { d.open = true; });
    }

    const cleanup = () => {
      document.title = prevTitle;
      detailsEls.forEach((d, i) => { d.open = prevOpen[i]; });
      document.body.classList.remove('kr-student-copy');
      window.removeEventListener('afterprint', cleanup);
    };
    window.addEventListener('afterprint', cleanup);
    window.print();
  }

  return (
    <span className="print:hidden inline-flex items-center gap-3">
      {showAnswersToggle && (
        <label className="inline-flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer select-none">
          <input
            type="checkbox"
            checked={includeAnswers}
            onChange={(e) => setIncludeAnswers(e.target.checked)}
            className="h-3.5 w-3.5 rounded border-border accent-primary"
          />
          Include answers &amp; marking guides
        </label>
      )}
      <button
        type="button"
        onClick={handlePrint}
        className="rounded-md border border-border bg-background px-3 py-1.5 text-xs font-medium hover:bg-muted transition-colors"
        title="Print or save as PDF"
      >
        Export PDF
      </button>
    </span>
  );
}

export function PrintHeader({
  school,
  documentKind,
  title,
  subtitle,
}: {
  school: School;
  documentKind: string;
  title: string;
  subtitle?: string;
}) {
  const logoUrl =
    school && school.logoUrl
      ? school.logoUrl.replace('/upload/', '/upload/w_96,h_96,c_fill,q_auto,f_auto/')
      : null;

  return (
    <>
      <div
        className="hidden print:block"
        style={{ borderBottom: `2px solid ${BRAND.green}`, paddingBottom: 12, marginBottom: 20 }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          {logoUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={logoUrl}
              alt=""
              width={48}
              height={48}
              style={{ width: 48, height: 48, objectFit: 'cover', borderRadius: 8 }}
            />
          ) : null}
          <div>
            <div style={{ color: BRAND.navy, fontWeight: 700, fontSize: 18, lineHeight: 1.2 }}>
              {(school && school.name) || 'School'}
            </div>
            <div style={{ color: BRAND.green, fontWeight: 700, fontSize: 13, marginTop: 2 }}>
              {documentKind}{title ? ` — ${title}` : ''}
            </div>
            {subtitle ? (
              <div style={{ color: BRAND.grey, fontSize: 11, marginTop: 2 }}>{subtitle}</div>
            ) : null}
          </div>
        </div>
      </div>
      <div className="kr-print-footer" aria-hidden="true">
        Generated by Klassrun · klassrun.com
      </div>
    </>
  );
}
